// Generated by functional.dev
//
// biome-ignore lint/style: auto-generated file
// eslint-disable
// prettier-ignore

/// <reference types="@cloudflare/workers-types" />

interface Env {
  APP_URL: string;
  ASSETS: Fetcher;
}