// Generated by functional.dev
//
// biome-ignore lint/style: auto-generated file
// eslint-disable
// prettier-ignore

/// <reference types="@cloudflare/workers-types" />

interface Env {
  MyHyperdrive: Hyperdrive;
  MyBucket: R2Bucket;
  KV_WITH_CUSTOM_BINDING_NAME: KVNamespace;
}