// Generated by functional.dev
//
// biome-ignore lint/style: auto-generated file
// eslint-disable
// prettier-ignore

/// <reference types="@cloudflare/workers-types" />

interface Env {
  TEST_PLAIN_TEXT: string;
  TEST_KV: KVNamespace;
}
